### ISSUE TITLE
No X button

### ISSUE THREAD

**Issue by ryanquincypaul** [athal7/dotfiles#4]
There's no X button. How am I supposed to just assume the X button is there? How do I close threads? Huge issue, definitely worth submitting a ticket on a personal dotfiles repo.

![image](https://user-images.githubusercontent.com/11447584/55639263-f6de8580-5796-11e9-8606-64fc3261f0d7.png)

Added the following at line 1089 of `ssb-interop.js` or `slack-ssb-interop.js` in your files:
```CSS
.p-threads_flexpane__header .c-icon--times:active, 
.p-threads_flexpane__header .c-icon--times:focus, 
.p-threads_flexpane__header .c-icon--times:hover,
.p-threads_flexpane__header .c-icon--times:before{
  color:white !important;
}
```

![image](https://user-images.githubusercontent.com/11447584/55639223-de6e6b00-5796-11e9-9497-2aa8392d7f2c.png)
